added error back in

diff --git a/snap/test1 b/snap/test1
--- a/snap/test1
+++ b/snap/test1
@@ -2,3 +2,4 @@
 
 echo "hi!" > test
 echo "not error"
+echo "error" >&2
