made shit output more

diff --git a/snap/test1 b/snap/test1
--- a/snap/test1
+++ b/snap/test1
@@ -1,3 +1,4 @@
 #!/bin/sh
 
 echo "hi!" > test
+echo "error" >&2
diff --git a/snap/test2 b/snap/test2
--- a/snap/test2
+++ b/snap/test2
@@ -1,3 +1,5 @@
 #!/bin/sh
 
 touch xblah
+echo "not an error"
+echo "error" >&2
