another error

diff --git a/snap/test1 b/snap/test1
--- a/snap/test1
+++ b/snap/test1
@@ -3,3 +3,4 @@
 echo "hi!" > test
 echo "not error"
 echo "error" >&2
+echo "another error" >&2
